### ISSUE TITLE
Tutorial 7 fails

### ISSUE THREAD

**Issue by morenoh149** [tomchristie/rest-framework-tutorial#27]
I get the following when I attempt tutorial 7. http://www.django-rest-framework.org/tutorial/7-schemas-and-client-libraries/

```bash
System check identified no issues (0 silenced).
July 19, 2016 - 19:12:01
Django version 1.8.5, using settings 'tutorial.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
Internal Server Error: /
Traceback (most recent call last):
  File "/Users/harrymoreno/programming/django/drfTutorial/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 119, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/Users/harrymoreno/programming/django/drfTutorial/venv/lib/python2.7/site-packages/django/core/urlresolvers.py", line 365, in resolve
    for pattern in self.url_patterns:
  File "/Users/harrymoreno/programming/django/drfTutorial/venv/lib/python2.7/site-packages/django/core/urlresolvers.py", line 401, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/Users/harrymoreno/programming/django/drfTutorial/venv/lib/python2.7/site-packages/django/core/urlresolvers.py", line 395, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/usr/local/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/harrymoreno/programming/django/rest-framework-tutorial/tutorial/urls.py", line 5, in <module>
    router = DefaultRouter(schema_title='foo')
TypeError: __init__() got an unexpected keyword argument 'schema_title'
```

**Comment by tomchristie** [comment]
You need to update your version of REST framework to 3.4
